### PR TITLE
Use config-file to define errorprone rule

### PR DESCRIPTION
**Pull request by snazy**
Also enabled a couple more simple rules, and adding suppressions/fixes for/to the code.

The two rules `EqualsGetClass` and `UnusedMethod`, which I think are useful, are not enabled yet, because that would mean actual code changes, which I do not want to do in this PR.

The rule `PatternMatchingInstanceof`, introduced in #393, is disabled in this PR. It does not work before errorrpone 2.37.0 (via #1213) - requires additional changes to enable the rule (see #1215).

### CODE REVIEW

**Comment by snazy** [comment]
Note: CI for #1213 would pass with this change.

**Review by eric-maynard — COMMENTED** [review]
This seems to not just be migrating to a config file, but also adding a lot of new checks?

**Comment by snazy** [comment]
Any objections to these rules?

**Review by dimas-b — APPROVED** [review]

**Comment by flyrain** [comment]
The main after-merge errors. It may be related. 
```
Execution failed for task ':polaris-service-common:compileJava'.
> Compilation failed; see the compiler output below.
  /home/runner/work/polaris/polaris/service/common/src/main/java/org/apache/polaris/service/catalog/common/CatalogHandler.java:223: error: [UseEnumSwitch] Prefer using a switch instead of a chained if-else for enums
        if (subType == PolarisEntitySubType.ICEBERG_TABLE) {
        ^
      (see https://errorprone.info/bugpattern/UseEnumSwitch)
    Did you mean 'switch (subType) {'?
  2 errors
```

**Comment by eric-maynard** [comment]
@HonahX I still see the same; why does `format` not automatically fix these or error out?

**Comment by dimas-b** [comment]
The project compiles fine in my env. after this PR.

**Comment by HonahX** [comment]
@eric-maynard Could you please share the error message you see? The main CI seems to pass too.

**Comment by eric-maynard** [comment]
It compiled fine on main for sure after @HonahX's fix.

However, check [this failed CI run on a dummy PR](https://github.com/apache/polaris/actions/runs/14285035248/job/40039071632?pr=1319) to see what I'm talking about. This is after running `./gradlew format`. What I'm saying is that it's possible for gradle format to pass but for there to still be formatting errors.
