### PR TITLE
Introduce multiple datasources

### PR DESCRIPTION
**Pull request by adutra**
This change enables multiple datasources in Polaris, with possibility of **runtime** activation of the desired datasource.

This is achieved by:

1) Introducing a new enabler property: `polaris.persistence.relational.jdbc.datasource`, which points to a named datasource to activate.

2) Declaring, **at build time**, one named datasource for each JDBC driver shipped with the application.

3) Introducing a new `DataSourceActivator` config interceptor that will, at runtime, change the `active` setting of the target datasource to `true`, and all others to `false` (`active` is a runtime setting, contrary to `db-kind`).

This change also makes the server ship with the H2 driver by default, since that's the pre-condition for an H2 datasource to be selected at runtime.

This change will further enable **as future improvements**:

- Using to JDBC + H2 by default for server images, while still allowing users to switch to PostgreSQL *without having to rebuild Polaris*.

- Enabling the persistence to "plug" into not one, but many datasources, e.g. a specific datasource for main persistence, and a separate datasource for metrics. This was outlined in https://github.com/apache/polaris/pull/3960 – but the machinery to make that happen was missing.

## Checklist
- [ ] 🛡️ Don't disclose security issues! (contact security@apache.org)
- [ ] 🔗 Clearly explained why the changes are needed, or linked related issues: Fixes #
- [ ] 🧪 Added/updated tests with good coverage, or manually tested (and explained how)
- [ ] 💡 Added comments for complex logic
- [ ] 🧾 Updated `CHANGELOG.md` (if needed)
- [ ] 📚 Updated documentation in `site/content/in-dev/unreleased` (if needed)

### CODE REVIEW

File: runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/JdbcProducers.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+  @Produces
+  @ApplicationScoped
+  public DatasourceOperations produceDatasourceOperations(
+      @Any Instance<DataSource> dataSources,
+      QuarkusRelationalJdbcConfiguration relationalJdbcConfiguration) {
+    String dataSourceName = relationalJdbcConfiguration.dataSource();
+    Instance<DataSource> dataSourceInstance = dataSources.select(NamedLiteral.of(dataSourceName));
+    if (dataSourceInstance.isUnsatisfied()) {
+      throw new IllegalStateException("datasource " + dataSourceName + " not found");
+    }
```
[the remark this answers is not in the document]
Comment (adutra) [reply runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/JdbcProducers.java]: Quarkus named datasources are qualified by both `@DataSource` and `@Named`.

[the remark this answers is not in the document]
Comment (adutra) [reply runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/JdbcProducers.java]: But OK, I will implement the suggestion and use `@DataSource`.

File: persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java [hunk 2]
```diff
@@ -93,13 +90,6 @@ public class JdbcMetaStoreManagerFactory implements MetaStoreManagerFactory {
 
   protected JdbcMetaStoreManagerFactory() {}
 
-  @Produces
-  @ApplicationScoped
-  static DatasourceOperations produceDatasourceOperations(
```
Comment (adutra) [inline persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java:98]: Moved to `polaris-runtime-common`.

File: persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/RelationalJdbcConfiguration.java [hunk 3]
```diff
@@ -21,18 +21,21 @@
...
   Optional<Long> initialDelayInMs();
 
   /**
    * Explicitly configured database type. If not specified, the database type will be inferred from
    * the JDBC connection metadata. Supported values: "postgresql", "cockroachdb", "h2"
    */
   Optional<String> databaseType();
+
+  /** The datasource name to use. Required. */
+  String dataSource();
```
Comment (adutra) [inline persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/RelationalJdbcConfiguration.java:40]: Note: the datasource name is distinct from the database type.

File: runtime/admin/src/main/resources/application.properties [hunk 4]
```diff
@@ -31,7 +31,12 @@ quarkus.container-image.registry=docker.io
 quarkus.container-image.group=apache
 quarkus.container-image.name=polaris-admin-tool
 quarkus.container-image.additional-tags=latest
-quarkus.datasource.db-kind=postgresql
+
+# Named datasources for relational persistence backends.
+# Polaris ships with many built-in datasources; by using named datasources, users can configure
+# at runtime which datasources to use for relational persistence backends.
+quarkus.datasource.postgresql.db-kind=postgresql
```
Comment (adutra) [inline runtime/admin/src/main/resources/application.properties:38]: The admin module does not ship H2, at least for now.

We may want to include H2 later. There are pros and cons:

- con: running the admin tool on an ephemeral database is meaningless
- pro: running the admin tool on an ephemeral database allows users to play with the different commands without having to configure a database.

File: runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/QuarkusRelationalJdbcConfiguration.java [hunk 5]
```diff
@@ -19,7 +19,34 @@
...
 import io.smallrye.config.ConfigMapping;
+import io.smallrye.config.WithName;
+import java.util.Optional;
 import org.apache.polaris.persistence.relational.jdbc.RelationalJdbcConfiguration;
 
 @ConfigMapping(prefix = "polaris.persistence.relational.jdbc")
-public interface QuarkusRelationalJdbcConfiguration extends RelationalJdbcConfiguration {}
+public interface QuarkusRelationalJdbcConfiguration extends RelationalJdbcConfiguration {
+
+  /** The maximum number of retries before giving up the operation. */
```
Comment (adutra) [inline runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/QuarkusRelationalJdbcConfiguration.java:29]: We need to repeat the javadocs here for them to appear in the docs.

File: runtime/server/distribution/LICENSE [hunk 6]
```diff
@@ -1781,6 +1782,21 @@ License: BSD 2-Clause
 
 --------------------------------------------------------------------------------
 
+This product bundles H2 JDBC Driver.
+
+* Maven group:artifact IDs: com.h2database:h2
+
+Project URL: https://www.h2database.com/
+License: Eclipse Public License 1.0 - https://www.eclipse.org/org/documents/epl-1.0/
```
Comment (adutra) [inline runtime/server/distribution/LICENSE:1792]: I picked EDL 1.0 since it's category A, while Mozilla is category B. @jbonofre @snazy is that OK?

File: runtime/server/build.gradle.kts [hunk 7]
```diff
@@ -37,6 +37,9 @@ dependencies {
   runtimeOnly("org.postgresql:postgresql")
   runtimeOnly(project(":polaris-relational-jdbc"))
   runtimeOnly("io.quarkus:quarkus-jdbc-postgresql")
+  runtimeOnly("io.quarkus:quarkus-jdbc-h2") {
+    exclude(group = "org.locationtech.jts", module = "jts-core")
```
Comment (adutra) [inline runtime/server/build.gradle.kts:42]: This dependency is for geometry types; we don't need it.

File: runtime/test-common/src/main/java/org/apache/polaris/test/commons/PostgresRelationalJdbcLifeCycleManagement.java [hunk 8]
```diff
@@ -61,16 +61,12 @@ public Map<String, String> start() {
     return Map.ofEntries(
         Map.entry("polaris.persistence.type", "relational-jdbc"),
         Map.entry("polaris.persistence.relational.jdbc.max-retries", "2"),
-        Map.entry("quarkus.datasource.db-kind", "postgresql"),
-        Map.entry("quarkus.datasource.jdbc.url", postgres.getJdbcUrl()),
-        Map.entry("quarkus.datasource.username", postgres.getUsername()),
-        Map.entry("quarkus.datasource.password", postgres.getPassword()),
-        Map.entry("quarkus.datasource.jdbc.initial-size", "10"),
-        // Configure metrics named datasource to use the same PostgreSQL instance
```
Comment (adutra) [inline runtime/test-common/src/main/java/org/apache/polaris/test/commons/PostgresRelationalJdbcLifeCycleManagement.java:69]: These "metric datasource" settings came as a surprise to me. I think it's an oversight; they were introduced by #3385 – but that PR does not implement separate datasources in its final form. Multiple datasources were attempted in #3960 (but it was closed without merging).

File: runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/DataSourceActivator.java [hunk 9]
```diff
@@ -0,0 +1,129 @@
...
+          active = dataSourceName.equals(targetDataSourceName(context));
+        }
+      } else {
+        // all datasources deactivated if persistence type is not relational-jdbc
+        active = false;
+      }
+      if (value == null
+          || value.getValue() == null
+          || active != Boolean.parseBoolean(value.getValue())) {
+        value = newConfigValue(value, Boolean.toString(active));
```
Comment (dimas-b) [inline runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/DataSourceActivator.java:77]: nit: why not do this unconditionally?

File: runtime/service/src/test/java/org/apache/polaris/service/events/listeners/inmemory/InMemoryBufferEventListenerIntegrationTest.java [hunk 10]
```diff
@@ -82,7 +83,9 @@ class InMemoryBufferEventListenerIntegrationTest {
   private String authToken;
   private URI baseLocation;
 
-  @Inject Instance<DataSource> dataSource;
+  @Inject
+  @DataSource("h2")
+  Instance<AgroalDataSource> dataSource;
```
Comment (dimas-b) [inline runtime/service/src/test/java/org/apache/polaris/service/events/listeners/inmemory/InMemoryBufferEventListenerIntegrationTest.java:88]: just wondering: why do we need to change the type here?

File: CHANGELOG.md [hunk 11]
```diff
@@ -28,6 +28,7 @@ request adding CHANGELOG notes for breaking (!) changes and possibly other secti
 ## [Unreleased]
 
 ### Highlights
+- Polaris now supports dynamic datasource activation. Out of the box, two datasources are provided: `postgresql` and `h2`. The datasource to use can be selected at runtime by setting the `polaris.persistence.relational.jdbc.datasource` configuration property (the default is `postgresql`). This allows operators to switch between supported relational databases without rebuilding Polaris.
```
Comment (dimas-b) [inline CHANGELOG.md]: Helm-based deployments are not affected by this change, right?

However, the Admin Tool and plain Polaris Server binaries are affected, I guess 🤔 Should we call this out as a "breaking change"?.. or at least add an "upgrade notice"?

**Review by dimas-b — DISMISSED** [review]

File: runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/DataSourceActivator.java (hunk 9 above)
Comment (adutra) [reply runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/DataSourceActivator.java:77]: To avoid tampering with the configuration if not absolutely necessary.

File: runtime/service/src/test/java/org/apache/polaris/service/events/listeners/inmemory/InMemoryBufferEventListenerIntegrationTest.java (hunk 10 above)
Comment (adutra) [reply runtime/service/src/test/java/org/apache/polaris/service/events/listeners/inmemory/InMemoryBufferEventListenerIntegrationTest.java:88]: Heh, we don't, but if you keep `DataSource`, there is an annoying clash between `java.sql.DataSource` and `io.quarkus.agroal.DataSource`.

File: runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/DataSourceActivator.java (hunk 9 above)
Comment (dimas-b) [reply runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/DataSourceActivator.java:77]: Yes, but it defers any potential bug discovery :thinking:

File: runtime/service/src/test/java/org/apache/polaris/service/events/listeners/inmemory/InMemoryBufferEventListenerIntegrationTest.java (hunk 10 above)
Comment (dimas-b) [reply runtime/service/src/test/java/org/apache/polaris/service/events/listeners/inmemory/InMemoryBufferEventListenerIntegrationTest.java:88]: ah, ok :+1:

File: CHANGELOG.md (hunk 11 above)
Comment (adutra) [reply CHANGELOG.md]: Hmm actually the Helm chart _is_ affected – but the admin tool isn't (H2 is not available there). Let me rephrase this sentence.

Re: breaking change: the inclusion of a new artifact is not a breaking change, is it? Imho this PR is not a breaking change.

Comment (dimas-b) [reply CHANGELOG.md]: By "breaking" I mean old `quarkus.*` config properties that users might have in their scripts/deployment descriptors.

Comment (adutra) [reply CHANGELOG.md]: But I agree that an upgrade notice could be welcome, let me add that.

Comment (adutra) [reply CHANGELOG.md]: Hmm OK, in fact I agree that the configuration changes constitute a breaking change.

File: CHANGELOG.md [hunk 12]
```diff
@@ -42,6 +44,7 @@ request adding CHANGELOG notes for breaking (!) changes and possibly other secti
     - Names containing control (invisible) characters
     - Names with leading or trailing whitespace
     - Names containing any of these characters: <code>/\:*?"<>|#+`</code>
+- Due to the introduction of dynamic datasource activation, the default (PostgreSQL) datasource is now unused. If you had any custom configuration for that datasource, it should be migrated from `quarkus.datasource.*` to `quarkus.datasource.postgresql.*`. The same is valid for environment variables: `QUARKUS_DATASOURCE_*` should be replaced with `QUARKUS_DATASOURCE_POSTGRESQL_*`.
```
Comment (dimas-b) [inline CHANGELOG.md:47]: This is a reasonable notice to users, IMHO... However, given that the 1.6.0 release is supposed to happen pretty soon, should we defer merging this PR until after 1.6.0 is branched?

**Review by dimas-b — DISMISSED** [review]

File: CHANGELOG.md (hunk 12 above)
Comment (adutra) [reply CHANGELOG.md:47]: Yes, that's reasonable. We can defer this to 1.7.0, which would then include the complete switch to JDBC+H2.

File: runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/DataSourceActivator.java (hunk 9 above)
Comment (adutra) [reply runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/DataSourceActivator.java:77]: Do you think so? I can't really imagine a situation where this would be concerning.

Comment (dimas-b) [reply runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/DataSourceActivator.java:77]: it's a "nit" comment, not a big deal :slightly_smiling_face:

File: persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java (hunk 2 above)
Comment (flyrain) [reply persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java:98]: This is probably for my information, why do we move it? Should this be part of JDBC module for better modularization?

Comment (adutra) [reply persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java:98]: I had a strong requirement for this move: the new producer method now needs to access `io.quarkus.agroal.DataSource.DataSourceLiteral`. I noticed that #3960 did the same move for similar reasons.

File: runtime/service/build.gradle.kts [hunk 13]
```diff
@@ -65,7 +65,12 @@ dependencies {
   implementation("io.quarkus:quarkus-security")
   implementation("io.quarkus:quarkus-smallrye-context-propagation")
   implementation("io.quarkus:quarkus-smallrye-fault-tolerance")
+
+  // JDBC backends
   runtimeOnly("io.quarkus:quarkus-jdbc-postgresql")
+  runtimeOnly("io.quarkus:quarkus-jdbc-h2") {
+    exclude(group = "org.locationtech.jts", module = "jts-core")
```
Comment (snazy) [inline runtime/service/build.gradle.kts:72]: Not excluding the dependency here?

File: runtime/defaults/src/main/resources/application-test.properties [hunk 14]
```diff
@@ -20,12 +20,20 @@
...
+polaris.persistence.type=in-memory
+quarkus.datasource.active=false
+quarkus.datasource.devservices.enabled=false
+quarkus.datasource.postgresql.devservices.enabled=false
+quarkus.datasource.h2.devservices.enabled=false
+
 # For unit tests, the default HTTP and management *test-ports* (8081 and 9001 respectively) must be
 # overridden to zero, so that Quarkus will automatically select an available port.
 quarkus.http.test-port=0
-quarkus.management.test-port=0
```
Comment (snazy) [inline runtime/defaults/src/main/resources/application-test.properties:26]: Accidental removal?

File: runtime/defaults/src/main/resources/application-test.properties [hunk 15]
```diff
@@ -20,12 +20,20 @@
...
+# (note: the test must be configured to use relational-jdbc persistence type).
+polaris.persistence.relational.jdbc.datasource=h2
+# Use in-memory persistence backend for unit tests by default.
+polaris.persistence.type=in-memory
+quarkus.datasource.active=false
+quarkus.datasource.devservices.enabled=false
+quarkus.datasource.postgresql.devservices.enabled=false
+quarkus.datasource.h2.devservices.enabled=false
+
 # For unit tests, the default HTTP and management *test-ports* (8081 and 9001 respectively) must be
```
Comment (snazy) [inline runtime/defaults/src/main/resources/application-test.properties:33]: Guess the port numbers are wrong (not from this PR though)

File: runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/QuarkusRelationalJdbcConfiguration.java (hunk 5 above)
Comment (snazy) [reply runtime/common/src/main/java/org/apache/polaris/quarkus/common/config/jdbc/QuarkusRelationalJdbcConfiguration.java:29]: Maybe follow-up work in the docs tooling.

File: runtime/admin/src/main/resources/application.properties (hunk 4 above)
Comment (snazy) [reply runtime/admin/src/main/resources/application.properties:38]: Not sure H2 helps - at least not as long it's only in-memory.

File: runtime/service/build.gradle.kts [hunk 16]
```diff
@@ -143,7 +148,10 @@ dependencies {
   testImplementation("io.quarkus:quarkus-junit-mockito")
   testImplementation("io.quarkus:quarkus-rest-client")
   testImplementation("io.quarkus:quarkus-rest-client-jackson")
-  testImplementation("io.quarkus:quarkus-jdbc-h2")
+  testImplementation("io.quarkus:quarkus-agroal")
+  testImplementation("io.quarkus:quarkus-jdbc-h2") {
+    exclude(group = "org.locationtech.jts", module = "jts-core")
```
Comment (snazy) [inline runtime/service/build.gradle.kts:153]: Same here

File: runtime/server/distribution/LICENSE (hunk 6 above)
Comment (snazy) [reply runtime/server/distribution/LICENSE:1792]: Slight correction: H2 is dual-licensed: E**P**L 1.0 and MPL 2.0 - both are category "B" and fine to be included in a binary convenience artifact.

File: site/content/in-dev/unreleased/metastores/relational-jdbc.md [hunk 17]
```diff
@@ -25,40 +25,99 @@ weight: 100
...
 ```properties
 polaris.persistence.type=relational-jdbc
-quarkus.datasource.jdbc.username=<your-username>
-quarkus.datasource.jdbc.password=<your-password>
-quarkus.datasource.jdbc.jdbc-url=<jdbc-url-of-postgres>
+polaris.persistence.relational.jdbc.datasource=postgresql
+
+quarkus.datasource.postgresql.jdbc.username=<your-username>
+quarkus.datasource.postgresql.jdbc.password=<your-password>
+quarkus.datasource.postgresql.jdbc.jdbc-url=<jdbc-url-of-postgres>
```
Comment (snazy) [inline site/content/in-dev/unreleased/metastores/relational-jdbc.md]:
```suggestion
quarkus.datasource.postgresql.username
quarkus.datasource.postgresql.password
quarkus.datasource.postgresql.jdbc.url
```

File: CHANGELOG.md (hunk 12 above)
Comment (snazy) [reply CHANGELOG.md:47]: Now that 1.6 is branches, I guess this is no longer a concern ;)

File: runtime/server/distribution/LICENSE (hunk 6 above)
Comment (adutra) [reply runtime/server/distribution/LICENSE:1792]: 🤦‍♂️ - sorry about the confusion.

File: runtime/defaults/src/main/resources/application-test.properties (hunk 14 above)
Comment (adutra) [reply runtime/defaults/src/main/resources/application-test.properties:26]: Yes, bad merge conflict resolution.

File: runtime/defaults/src/main/resources/application-test.properties (hunk 15 above)
Comment (adutra) [reply runtime/defaults/src/main/resources/application-test.properties:33]: They are not, in fact. These are the default values for `quarkus.http.test-port` and `quarkus.management.test-port` respectively.

**Review by snazy — APPROVED** [review]

**Review by dimas-b — APPROVED** [review]

File: CHANGELOG.md (hunk 12 above)
Comment (dimas-b) [reply CHANGELOG.md:47]: Agreed: +1 to merge to `main` now.
